name: 🚀 Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish the packages
    permissions:
      id-token: write
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files to the repository.
      # Also required for uploading files to the Release assets
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 📄 Upload LICENSE file to release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: LICENSE

      - name: 🛠️ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: 🔍 Verify Flutter installation
        run: flutter --version

      - name: 📥 Install Flutter dependencies
        run: flutter pub get
      
      # This is needed in order for the authentication to success
      # dart pub token add https://pub.dev --env-var PUB_TOKEN
      # Requests to "https://pub.dev" will now be authenticated using the secret token stored in the environment variable "PUB_TOKEN".
      - name: 🏗️ Set up Dart environment
        uses: dart-lang/setup-dart@v1
      ## dart-lang/setup-dart/.github/workflows/publish.yml@v1
      # - name: Update the authorization requests to "https://pub.dev" to use the environment variable "PUB_TOKEN".
      #   run: dart pub token add https://pub.dev --env-var PUB_TOKEN

      

      - name: 🔄 Check if package is ready for publishing
        run: flutter pub publish --dry-run

      - name: 📤 Publish flutter_quill
        run: flutter pub publish --force

      - name: 📤 Publish flutter_quill_extensions
        run: flutter pub publish --force
        working-directory: ./flutter_quill_extensions/

      - name: 📤 Publish flutter_quill_test
        run: flutter pub publish --force
        working-directory: ./flutter_quill_test/

